allowBuilds:
  esbuild: true
  msw: true

overrides:
  "@mjackson/node-fetch-server": "npm:@remix-run/node-fetch-server@^0.14.0"
  "browserslist@<=4.28.6": 4.28.9
  "fast-uri@>=3.0.0 <3.1.6": 3.1.7
  "lodash-es@<=4.17.23": 4.18.1
