name: Continuous Integration 🤖

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the branch 🤖
        uses: actions/checkout@v3

      - name: Setup Node 🤖
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies 🤖
        run: npm ci --force

      - name: Build the code 🤖
        run: npm run build:web

      - name: Run unit tests 🤖
        run: npm run test:unit
